// Generated by scripts/sync-perfect-core-reference.mjs.
export const referenceSkillSeeds = {
  "dark-knight": [
    {
      "id": "dark-knight-300626",
      "name": "最终之击",
      "iconUrl": "/assets/skills/dark-knight/300626.png",
      "sortOrder": 0
    },
    {
      "id": "dark-knight-300018",
      "name": "神矛天引",
      "iconUrl": "/assets/skills/dark-knight/300018.png",
      "sortOrder": 1
    },
    {
      "id": "dark-knight-300406",
      "name": "眼魔",
      "iconUrl": "/assets/skills/dark-knight/300406.png",
      "sortOrder": 2
    },
    {
      "id": "dark-knight-300038",
      "name": "拉曼查之枪",
      "iconUrl": "/assets/skills/dark-knight/300038.png",
      "sortOrder": 3
    },
    {
      "id": "dark-knight-300048",
      "name": "突进/飞跃一击/冲天击",
      "iconUrl": "/assets/skills/dark-knight/300048.png",
      "sortOrder": 4
    },
    {
      "id": "dark-knight-300073",
      "name": "黑暗穿刺",
      "iconUrl": "/assets/skills/dark-knight/300073.png",
      "sortOrder": 5
    },
    {
      "id": "dark-knight-300083",
      "name": "永恒之枪",
      "iconUrl": "/assets/skills/dark-knight/300083.png",
      "sortOrder": 6
    },
    {
      "id": "dark-knight-300201",
      "name": "黑暗融合",
      "iconUrl": "/assets/skills/dark-knight/300201.png",
      "sortOrder": 7
    }
  ],
  "bowmaster": [
    {
      "id": "bowmaster-309001",
      "name": "风之矢",
      "iconUrl": "/assets/skills/bowmaster/309001.png",
      "sortOrder": 0
    },
    {
      "id": "bowmaster-309401",
      "name": "三彩箭矢",
      "iconUrl": "/assets/skills/bowmaster/309401.png",
      "sortOrder": 1
    },
    {
      "id": "bowmaster-309631",
      "name": "最终之击：弓",
      "iconUrl": "/assets/skills/bowmaster/309631.png",
      "sortOrder": 2
    },
    {
      "id": "bowmaster-309011",
      "name": "箭矢炮盘/蜃影闪现",
      "iconUrl": "/assets/skills/bowmaster/309011.png",
      "sortOrder": 3
    },
    {
      "id": "bowmaster-309205",
      "name": "疾风箭",
      "iconUrl": "/assets/skills/bowmaster/309205.png",
      "sortOrder": 4
    },
    {
      "id": "bowmaster-309031",
      "name": "火凤凰",
      "iconUrl": "/assets/skills/bowmaster/309031.png",
      "sortOrder": 5
    },
    {
      "id": "bowmaster-309301",
      "name": "后撤跳疾射",
      "iconUrl": "/assets/skills/bowmaster/309301.png",
      "sortOrder": 6
    },
    {
      "id": "bowmaster-309051",
      "name": "骤雨箭矢",
      "iconUrl": "/assets/skills/bowmaster/309051.png",
      "sortOrder": 7
    },
    {
      "id": "bowmaster-309311",
      "name": "暴风箭雨",
      "iconUrl": "/assets/skills/bowmaster/309311.png",
      "sortOrder": 8
    },
    {
      "id": "bowmaster-309225",
      "name": "裂羽之风",
      "iconUrl": "/assets/skills/bowmaster/309225.png",
      "sortOrder": 9
    }
  ],
  "night-lord": [
    {
      "id": "night-lord-303611",
      "name": "猎手标记",
      "iconUrl": "/assets/skills/night-lord/303611.png",
      "sortOrder": 0
    },
    {
      "id": "night-lord-303105",
      "name": "爆裂飞镖",
      "iconUrl": "/assets/skills/night-lord/303105.png",
      "sortOrder": 1
    },
    {
      "id": "night-lord-303115",
      "name": "风之护符",
      "iconUrl": "/assets/skills/night-lord/303115.png",
      "sortOrder": 2
    },
    {
      "id": "night-lord-303125",
      "name": "三连环光击破",
      "iconUrl": "/assets/skills/night-lord/303125.png",
      "sortOrder": 3
    },
    {
      "id": "night-lord-303014",
      "name": "飞镖决战",
      "iconUrl": "/assets/skills/night-lord/303014.png",
      "sortOrder": 4
    },
    {
      "id": "night-lord-303024",
      "name": "黑暗闪击",
      "iconUrl": "/assets/skills/night-lord/303024.png",
      "sortOrder": 5
    },
    {
      "id": "night-lord-303135",
      "name": "四连镖",
      "iconUrl": "/assets/skills/night-lord/303135.png",
      "sortOrder": 6
    },
    {
      "id": "night-lord-303148",
      "name": "突然袭击",
      "iconUrl": "/assets/skills/night-lord/303148.png",
      "sortOrder": 7
    },
    {
      "id": "night-lord-303029",
      "name": "决战之巅",
      "iconUrl": "/assets/skills/night-lord/303029.png",
      "sortOrder": 8
    },
    {
      "id": "night-lord-303147",
      "name": "四季飞镖",
      "iconUrl": "/assets/skills/night-lord/303147.png",
      "sortOrder": 9
    }
  ],
  "bishop": [
    {
      "id": "bishop-306021",
      "name": "天愈之触",
      "iconUrl": "/assets/skills/bishop/306021.png",
      "sortOrder": 0
    },
    {
      "id": "bishop-306001",
      "name": "光明之箭",
      "iconUrl": "/assets/skills/bishop/306001.png",
      "sortOrder": 1
    },
    {
      "id": "bishop-306031",
      "name": "光之翼",
      "iconUrl": "/assets/skills/bishop/306031.png",
      "sortOrder": 2
    },
    {
      "id": "bishop-306225",
      "name": "创世之破",
      "iconUrl": "/assets/skills/bishop/306225.png",
      "sortOrder": 3
    },
    {
      "id": "bishop-306215",
      "name": "光芒飞箭",
      "iconUrl": "/assets/skills/bishop/306215.png",
      "sortOrder": 4
    },
    {
      "id": "bishop-306071",
      "name": "神龙召唤",
      "iconUrl": "/assets/skills/bishop/306071.png",
      "sortOrder": 5
    },
    {
      "id": "bishop-306235",
      "name": "天怒/胜利之羽",
      "iconUrl": "/assets/skills/bishop/306235.png",
      "sortOrder": 6
    },
    {
      "id": "bishop-306245",
      "name": "光辉之门/天罚之泉",
      "iconUrl": "/assets/skills/bishop/306245.png",
      "sortOrder": 7
    }
  ],
  "corsair": [
    {
      "id": "corsair-311016",
      "name": "快枪手",
      "iconUrl": "/assets/skills/corsair/311016.png",
      "sortOrder": 0
    },
    {
      "id": "corsair-311225",
      "name": "脱离战场",
      "iconUrl": "/assets/skills/corsair/311225.png",
      "sortOrder": 1
    },
    {
      "id": "corsair-311096",
      "name": "召唤船员/集合船员",
      "iconUrl": "/assets/skills/corsair/311096.png",
      "sortOrder": 2
    },
    {
      "id": "corsair-311046",
      "name": "攻城大炮",
      "iconUrl": "/assets/skills/corsair/311046.png",
      "sortOrder": 3
    },
    {
      "id": "corsair-311026",
      "name": "双管枪射击",
      "iconUrl": "/assets/skills/corsair/311026.png",
      "sortOrder": 4
    },
    {
      "id": "corsair-311036",
      "name": "冲撞弹",
      "iconUrl": "/assets/skills/corsair/311036.png",
      "sortOrder": 5
    },
    {
      "id": "corsair-311056",
      "name": "齐射",
      "iconUrl": "/assets/skills/corsair/311056.png",
      "sortOrder": 6
    },
    {
      "id": "corsair-311081",
      "name": "战舰炮轰/炮击记号",
      "iconUrl": "/assets/skills/corsair/311081.png",
      "sortOrder": 7
    },
    {
      "id": "corsair-311066",
      "name": "精准射击",
      "iconUrl": "/assets/skills/corsair/311066.png",
      "sortOrder": 8
    },
    {
      "id": "corsair-311401",
      "name": "金属风暴",
      "iconUrl": "/assets/skills/corsair/311401.png",
      "sortOrder": 9
    },
    {
      "id": "corsair-311656",
      "name": "船长的威严",
      "iconUrl": "/assets/skills/corsair/311656.png",
      "sortOrder": 10
    },
    {
      "id": "corsair-311255",
      "name": "诺特勒斯战舰",
      "iconUrl": "/assets/skills/corsair/311255.png",
      "sortOrder": 11
    },
    {
      "id": "corsair-311245",
      "name": "无尽追击",
      "iconUrl": "/assets/skills/corsair/311245.png",
      "sortOrder": 12
    },
    {
      "id": "corsair-311265",
      "name": "奇异炸弹",
      "iconUrl": "/assets/skills/corsair/311265.png",
      "sortOrder": 13
    }
  ],
  "dawn-warrior": [
    {
      "id": "dawn-warrior-77045",
      "name": "猛袭",
      "iconUrl": "/assets/skills/dawn-warrior/77045.png",
      "sortOrder": 0
    },
    {
      "id": "dawn-warrior-77221",
      "name": "宇宙物质",
      "iconUrl": "/assets/skills/dawn-warrior/77221.png",
      "sortOrder": 1
    },
    {
      "id": "dawn-warrior-77093",
      "name": "炽日流火",
      "iconUrl": "/assets/skills/dawn-warrior/77093.png",
      "sortOrder": 2
    },
    {
      "id": "dawn-warrior-77251",
      "name": "宇宙爆裂",
      "iconUrl": "/assets/skills/dawn-warrior/77251.png",
      "sortOrder": 3
    },
    {
      "id": "dawn-warrior-77005",
      "name": "太阳抨击",
      "iconUrl": "/assets/skills/dawn-warrior/77005.png",
      "sortOrder": 4
    },
    {
      "id": "dawn-warrior-77083",
      "name": "日月斩",
      "iconUrl": "/assets/skills/dawn-warrior/77083.png",
      "sortOrder": 5
    },
    {
      "id": "dawn-warrior-77261",
      "name": "落魂剑",
      "iconUrl": "/assets/skills/dawn-warrior/77261.png",
      "sortOrder": 6
    },
    {
      "id": "dawn-warrior-77035",
      "name": "宇宙星流",
      "iconUrl": "/assets/skills/dawn-warrior/77035.png",
      "sortOrder": 7
    }
  ],
  "wind-archer": [
    {
      "id": "wind-archer-80001",
      "name": "清风箭",
      "iconUrl": "/assets/skills/wind-archer/80001.png",
      "sortOrder": 0
    },
    {
      "id": "wind-archer-80315",
      "name": "破风箭",
      "iconUrl": "/assets/skills/wind-archer/80315.png",
      "sortOrder": 1
    },
    {
      "id": "wind-archer-80305",
      "name": "疾风箭",
      "iconUrl": "/assets/skills/wind-archer/80305.png",
      "sortOrder": 2
    },
    {
      "id": "wind-archer-80821",
      "name": "狂风肆虐/风暴无常",
      "iconUrl": "/assets/skills/wind-archer/80821.png",
      "sortOrder": 3
    },
    {
      "id": "wind-archer-80325",
      "name": "精准箭",
      "iconUrl": "/assets/skills/wind-archer/80325.png",
      "sortOrder": 4
    },
    {
      "id": "wind-archer-80016",
      "name": "风霜雪舞",
      "iconUrl": "/assets/skills/wind-archer/80016.png",
      "sortOrder": 5
    },
    {
      "id": "wind-archer-80401",
      "name": "天空之歌",
      "iconUrl": "/assets/skills/wind-archer/80401.png",
      "sortOrder": 6
    },
    {
      "id": "wind-archer-80046",
      "name": "仙灵回旋",
      "iconUrl": "/assets/skills/wind-archer/80046.png",
      "sortOrder": 7
    },
    {
      "id": "wind-archer-80506",
      "name": "暴风灭世",
      "iconUrl": "/assets/skills/wind-archer/80506.png",
      "sortOrder": 8
    },
    {
      "id": "wind-archer-80056",
      "name": "季风",
      "iconUrl": "/assets/skills/wind-archer/80056.png",
      "sortOrder": 9
    }
  ],
  "night-walker": [
    {
      "id": "night-walker-78506",
      "name": "暗影蝙蝠/贪婪蝙蝠",
      "iconUrl": "/assets/skills/night-walker/78506.png",
      "sortOrder": 0
    },
    {
      "id": "night-walker-78001",
      "name": "幸运飞镖",
      "iconUrl": "/assets/skills/night-walker/78001.png",
      "sortOrder": 1
    },
    {
      "id": "night-walker-78401",
      "name": "三连环光击破",
      "iconUrl": "/assets/skills/night-walker/78401.png",
      "sortOrder": 2
    },
    {
      "id": "night-walker-78421",
      "name": "四连镖",
      "iconUrl": "/assets/skills/night-walker/78421.png",
      "sortOrder": 3
    },
    {
      "id": "night-walker-78205",
      "name": "碎星镖",
      "iconUrl": "/assets/skills/night-walker/78205.png",
      "sortOrder": 4
    },
    {
      "id": "night-walker-78016",
      "name": "黑暗预兆",
      "iconUrl": "/assets/skills/night-walker/78016.png",
      "sortOrder": 5
    },
    {
      "id": "night-walker-78466",
      "name": "暗影缚魂",
      "iconUrl": "/assets/skills/night-walker/78466.png",
      "sortOrder": 6
    },
    {
      "id": "night-walker-78446",
      "name": "五连镖",
      "iconUrl": "/assets/skills/night-walker/78446.png",
      "sortOrder": 7
    },
    {
      "id": "night-walker-78215",
      "name": "黑暗领域",
      "iconUrl": "/assets/skills/night-walker/78215.png",
      "sortOrder": 8
    }
  ],
  "flame-wizard": [
    {
      "id": "flame-wizard-79101",
      "name": "轨道烈焰",
      "iconUrl": "/assets/skills/flame-wizard/79101.png",
      "sortOrder": 0
    },
    {
      "id": "flame-wizard-79001",
      "name": "烈焰冲击",
      "iconUrl": "/assets/skills/flame-wizard/79001.png",
      "sortOrder": 1
    },
    {
      "id": "flame-wizard-79011",
      "name": "烈焰漩涡",
      "iconUrl": "/assets/skills/flame-wizard/79011.png",
      "sortOrder": 2
    },
    {
      "id": "flame-wizard-79501",
      "name": "轨道爆裂",
      "iconUrl": "/assets/skills/flame-wizard/79501.png",
      "sortOrder": 3
    },
    {
      "id": "flame-wizard-79031",
      "name": "烈焰风暴",
      "iconUrl": "/assets/skills/flame-wizard/79031.png",
      "sortOrder": 4
    },
    {
      "id": "flame-wizard-79041",
      "name": "大漩涡",
      "iconUrl": "/assets/skills/flame-wizard/79041.png",
      "sortOrder": 5
    },
    {
      "id": "flame-wizard-79051",
      "name": "灭绝之焰",
      "iconUrl": "/assets/skills/flame-wizard/79051.png",
      "sortOrder": 6
    },
    {
      "id": "flame-wizard-79305",
      "name": "地狱火海",
      "iconUrl": "/assets/skills/flame-wizard/79305.png",
      "sortOrder": 7
    },
    {
      "id": "flame-wizard-79526",
      "name": "凤凰重击",
      "iconUrl": "/assets/skills/flame-wizard/79526.png",
      "sortOrder": 8
    },
    {
      "id": "flame-wizard-79325",
      "name": "灭顶之灾",
      "iconUrl": "/assets/skills/flame-wizard/79325.png",
      "sortOrder": 9
    }
  ],
  "thunder-breaker": [
    {
      "id": "thunder-breaker-81005",
      "name": "闪电冲击",
      "iconUrl": "/assets/skills/thunder-breaker/81005.png",
      "sortOrder": 0
    },
    {
      "id": "thunder-breaker-81301",
      "name": "电光突袭",
      "iconUrl": "/assets/skills/thunder-breaker/81301.png",
      "sortOrder": 1
    },
    {
      "id": "thunder-breaker-81015",
      "name": "鲨之回旋",
      "iconUrl": "/assets/skills/thunder-breaker/81015.png",
      "sortOrder": 2
    },
    {
      "id": "thunder-breaker-81025",
      "name": "波涛/海浪",
      "iconUrl": "/assets/skills/thunder-breaker/81025.png",
      "sortOrder": 3
    },
    {
      "id": "thunder-breaker-81035",
      "name": "冲天",
      "iconUrl": "/assets/skills/thunder-breaker/81035.png",
      "sortOrder": 4
    },
    {
      "id": "thunder-breaker-81045",
      "name": "雷鸣",
      "iconUrl": "/assets/skills/thunder-breaker/81045.png",
      "sortOrder": 5
    },
    {
      "id": "thunder-breaker-81055",
      "name": "疾风",
      "iconUrl": "/assets/skills/thunder-breaker/81055.png",
      "sortOrder": 6
    },
    {
      "id": "thunder-breaker-81075",
      "name": "霹雳",
      "iconUrl": "/assets/skills/thunder-breaker/81075.png",
      "sortOrder": 7
    },
    {
      "id": "thunder-breaker-81065",
      "name": "毁灭",
      "iconUrl": "/assets/skills/thunder-breaker/81065.png",
      "sortOrder": 8
    },
    {
      "id": "thunder-breaker-81201",
      "name": "海神降临",
      "iconUrl": "/assets/skills/thunder-breaker/81201.png",
      "sortOrder": 9
    }
  ],
  "aran": [
    {
      "id": "aran-26606",
      "name": "斗气重击",
      "iconUrl": "/assets/skills/aran/26606.png",
      "sortOrder": 0
    },
    {
      "id": "aran-26361",
      "name": "斗气冲击",
      "iconUrl": "/assets/skills/aran/26361.png",
      "sortOrder": 1
    },
    {
      "id": "aran-26025",
      "name": "战神突进",
      "iconUrl": "/assets/skills/aran/26025.png",
      "sortOrder": 2
    },
    {
      "id": "aran-26055",
      "name": "终极投掷",
      "iconUrl": "/assets/skills/aran/26055.png",
      "sortOrder": 3
    },
    {
      "id": "aran-26621",
      "name": "最终之击",
      "iconUrl": "/assets/skills/aran/26621.png",
      "sortOrder": 4
    },
    {
      "id": "aran-26165",
      "name": "聚集捕手",
      "iconUrl": "/assets/skills/aran/26165.png",
      "sortOrder": 5
    },
    {
      "id": "aran-26085",
      "name": "旋风",
      "iconUrl": "/assets/skills/aran/26085.png",
      "sortOrder": 6
    },
    {
      "id": "aran-26411",
      "name": "巨熊咆哮",
      "iconUrl": "/assets/skills/aran/26411.png",
      "sortOrder": 7
    },
    {
      "id": "aran-26115",
      "name": "摩诃审判",
      "iconUrl": "/assets/skills/aran/26115.png",
      "sortOrder": 8
    },
    {
      "id": "aran-26197",
      "name": "比昂德",
      "iconUrl": "/assets/skills/aran/26197.png",
      "sortOrder": 9
    },
    {
      "id": "aran-26331",
      "name": "极速巅峰 - 恐惧风暴",
      "iconUrl": "/assets/skills/aran/26331.png",
      "sortOrder": 10
    },
    {
      "id": "aran-26311",
      "name": "极速巅峰 - 瞄准猎物",
      "iconUrl": "/assets/skills/aran/26311.png",
      "sortOrder": 11
    },
    {
      "id": "aran-26381",
      "name": "摩诃领域",
      "iconUrl": "/assets/skills/aran/26381.png",
      "sortOrder": 12
    }
  ],
  "mercedes": [
    {
      "id": "mercedes-27405",
      "name": "快速二连射/穿透之箭",
      "iconUrl": "/assets/skills/mercedes/27405.png",
      "sortOrder": 0
    },
    {
      "id": "mercedes-27301",
      "name": "升龙突击/终结箭/爆裂飞腿/旋转月瀑坠击",
      "iconUrl": "/assets/skills/mercedes/27301.png",
      "sortOrder": 1
    },
    {
      "id": "mercedes-27415",
      "name": "急袭双击/终极：双弩枪",
      "iconUrl": "/assets/skills/mercedes/27415.png",
      "sortOrder": 2
    },
    {
      "id": "mercedes-27021",
      "name": "飞叶旋风/狂风俯冲",
      "iconUrl": "/assets/skills/mercedes/27021.png",
      "sortOrder": 3
    },
    {
      "id": "mercedes-27031",
      "name": "独角兽冲刺",
      "iconUrl": "/assets/skills/mercedes/27031.png",
      "sortOrder": 4
    },
    {
      "id": "mercedes-27516",
      "name": "精灵骑士",
      "iconUrl": "/assets/skills/mercedes/27516.png",
      "sortOrder": 5
    },
    {
      "id": "mercedes-27311",
      "name": "伊师塔之环",
      "iconUrl": "/assets/skills/mercedes/27311.png",
      "sortOrder": 6
    },
    {
      "id": "mercedes-27076",
      "name": "传说之矛",
      "iconUrl": "/assets/skills/mercedes/27076.png",
      "sortOrder": 7
    },
    {
      "id": "mercedes-27086",
      "name": "闪电刀刃",
      "iconUrl": "/assets/skills/mercedes/27086.png",
      "sortOrder": 8
    },
    {
      "id": "mercedes-27116",
      "name": "恩利尔之怒",
      "iconUrl": "/assets/skills/mercedes/27116.png",
      "sortOrder": 9
    }
  ],
  "evan": [
    {
      "id": "evan-28611",
      "name": "飞龙闪",
      "iconUrl": "/assets/skills/evan/28611.png",
      "sortOrder": 0
    },
    {
      "id": "evan-28001",
      "name": "魔力之环1",
      "iconUrl": "/assets/skills/evan/28001.png",
      "sortOrder": 1
    },
    {
      "id": "evan-28011",
      "name": "狂风之环",
      "iconUrl": "/assets/skills/evan/28011.png",
      "sortOrder": 2
    },
    {
      "id": "evan-28021",
      "name": "巨龙迅捷",
      "iconUrl": "/assets/skills/evan/28021.png",
      "sortOrder": 3
    },
    {
      "id": "evan-28052",
      "name": "雷电之环",
      "iconUrl": "/assets/skills/evan/28052.png",
      "sortOrder": 4
    },
    {
      "id": "evan-28062",
      "name": "巨龙俯冲",
      "iconUrl": "/assets/skills/evan/28062.png",
      "sortOrder": 5
    },
    {
      "id": "evan-28112",
      "name": "魔法残骸",
      "iconUrl": "/assets/skills/evan/28112.png",
      "sortOrder": 6
    },
    {
      "id": "evan-28425",
      "name": "黑暗迷雾",
      "iconUrl": "/assets/skills/evan/28425.png",
      "sortOrder": 7
    },
    {
      "id": "evan-28127",
      "name": "大地之环",
      "iconUrl": "/assets/skills/evan/28127.png",
      "sortOrder": 8
    },
    {
      "id": "evan-28137",
      "name": "巨龙吐息",
      "iconUrl": "/assets/skills/evan/28137.png",
      "sortOrder": 9
    },
    {
      "id": "evan-28209",
      "name": "召唤玛瑙龙",
      "iconUrl": "/assets/skills/evan/28209.png",
      "sortOrder": 10
    },
    {
      "id": "evan-28207",
      "name": "龙神归来",
      "iconUrl": "/assets/skills/evan/28207.png",
      "sortOrder": 11
    }
  ],
  "luminous": [
    {
      "id": "luminous-29001",
      "name": "耀眼光球",
      "iconUrl": "/assets/skills/luminous/29001.png",
      "sortOrder": 0
    },
    {
      "id": "luminous-29011",
      "name": "黑暗坠落",
      "iconUrl": "/assets/skills/luminous/29011.png",
      "sortOrder": 1
    },
    {
      "id": "luminous-29405",
      "name": "光明长枪",
      "iconUrl": "/assets/skills/luminous/29405.png",
      "sortOrder": 2
    },
    {
      "id": "luminous-29021",
      "name": "虚空之眼",
      "iconUrl": "/assets/skills/luminous/29021.png",
      "sortOrder": 3
    },
    {
      "id": "luminous-29036",
      "name": "超级光谱",
      "iconUrl": "/assets/skills/luminous/29036.png",
      "sortOrder": 4
    },
    {
      "id": "luminous-29046",
      "name": "闪耀救赎",
      "iconUrl": "/assets/skills/luminous/29046.png",
      "sortOrder": 5
    },
    {
      "id": "luminous-29056",
      "name": "黑暗之锚",
      "iconUrl": "/assets/skills/luminous/29056.png",
      "sortOrder": 6
    },
    {
      "id": "luminous-29415",
      "name": "猎魂之镰",
      "iconUrl": "/assets/skills/luminous/29415.png",
      "sortOrder": 7
    },
    {
      "id": "luminous-29425",
      "name": "闪电反击",
      "iconUrl": "/assets/skills/luminous/29425.png",
      "sortOrder": 8
    },
    {
      "id": "luminous-29066",
      "name": "暮光新星",
      "iconUrl": "/assets/skills/luminous/29066.png",
      "sortOrder": 9
    },
    {
      "id": "luminous-29435",
      "name": "启示录",
      "iconUrl": "/assets/skills/luminous/29435.png",
      "sortOrder": 10
    },
    {
      "id": "luminous-29445",
      "name": "绝对制裁",
      "iconUrl": "/assets/skills/luminous/29445.png",
      "sortOrder": 11
    },
    {
      "id": "luminous-29455",
      "name": "末日审判",
      "iconUrl": "/assets/skills/luminous/29455.png",
      "sortOrder": 12
    }
  ],
  "hero": [
    {
      "id": "hero-301018",
      "name": "轻舞飞扬",
      "iconUrl": "/assets/skills/hero/301018.png",
      "sortOrder": 0
    },
    {
      "id": "hero-301028",
      "name": "暗影斩",
      "iconUrl": "/assets/skills/hero/301028.png",
      "sortOrder": 1
    },
    {
      "id": "hero-301621",
      "name": "最终之击",
      "iconUrl": "/assets/skills/hero/301621.png",
      "sortOrder": 2
    },
    {
      "id": "hero-301118",
      "name": "勇猛劈砍",
      "iconUrl": "/assets/skills/hero/301118.png",
      "sortOrder": 3
    },
    {
      "id": "hero-301128",
      "name": "突进/飞跃一击/冲天击",
      "iconUrl": "/assets/skills/hero/301128.png",
      "sortOrder": 4
    },
    {
      "id": "hero-301517",
      "name": "战士意念",
      "iconUrl": "/assets/skills/hero/301517.png",
      "sortOrder": 5
    },
    {
      "id": "hero-301301",
      "name": "灵刃双月",
      "iconUrl": "/assets/skills/hero/301301.png",
      "sortOrder": 6
    },
    {
      "id": "hero-301138",
      "name": "终极打击",
      "iconUrl": "/assets/skills/hero/301138.png",
      "sortOrder": 7
    },
    {
      "id": "hero-301158",
      "name": "烈焰冲斩",
      "iconUrl": "/assets/skills/hero/301158.png",
      "sortOrder": 8
    },
    {
      "id": "hero-301391",
      "name": "狂怒连爆",
      "iconUrl": "/assets/skills/hero/301391.png",
      "sortOrder": 9
    }
  ],
  "marksman": [
    {
      "id": "marksman-310621",
      "name": "最终之击：弩",
      "iconUrl": "/assets/skills/marksman/310621.png",
      "sortOrder": 0
    },
    {
      "id": "marksman-310205",
      "name": "疾风箭",
      "iconUrl": "/assets/skills/marksman/310205.png",
      "sortOrder": 1
    },
    {
      "id": "marksman-310001",
      "name": "迅捷闪电/冰凤凰",
      "iconUrl": "/assets/skills/marksman/310001.png",
      "sortOrder": 2
    },
    {
      "id": "marksman-310401",
      "name": "后撤跳疾射",
      "iconUrl": "/assets/skills/marksman/310401.png",
      "sortOrder": 3
    },
    {
      "id": "marksman-310646",
      "name": "穿透箭-增强/穿透箭",
      "iconUrl": "/assets/skills/marksman/310646.png",
      "sortOrder": 4
    },
    {
      "id": "marksman-310676",
      "name": "狙击箭-增强/狙击箭",
      "iconUrl": "/assets/skills/marksman/310676.png",
      "sortOrder": 5
    },
    {
      "id": "marksman-310285",
      "name": "超远距狙击/神箭幻影",
      "iconUrl": "/assets/skills/marksman/310285.png",
      "sortOrder": 6
    }
  ],
  "shadower": [
    {
      "id": "shadower-304015",
      "name": "回旋斩",
      "iconUrl": "/assets/skills/shadower/304015.png",
      "sortOrder": 0
    },
    {
      "id": "shadower-304025",
      "name": "刀刃之舞",
      "iconUrl": "/assets/skills/shadower/304025.png",
      "sortOrder": 1
    },
    {
      "id": "shadower-304045",
      "name": "金钱炸弹/暗影炸弹",
      "iconUrl": "/assets/skills/shadower/304045.png",
      "sortOrder": 2
    },
    {
      "id": "shadower-304035",
      "name": "炼狱",
      "iconUrl": "/assets/skills/shadower/304035.png",
      "sortOrder": 3
    },
    {
      "id": "shadower-304065",
      "name": "黑暗闪击",
      "iconUrl": "/assets/skills/shadower/304065.png",
      "sortOrder": 4
    },
    {
      "id": "shadower-304070",
      "name": "暗影闪猎",
      "iconUrl": "/assets/skills/shadower/304070.png",
      "sortOrder": 5
    },
    {
      "id": "shadower-304100",
      "name": "瞬影进击",
      "iconUrl": "/assets/skills/shadower/304100.png",
      "sortOrder": 6
    },
    {
      "id": "shadower-304201",
      "name": "突然袭击",
      "iconUrl": "/assets/skills/shadower/304201.png",
      "sortOrder": 7
    },
    {
      "id": "shadower-304115",
      "name": "潜影伏兵",
      "iconUrl": "/assets/skills/shadower/304115.png",
      "sortOrder": 8
    }
  ],
  "paladin": [
    {
      "id": "paladin-302622",
      "name": "最终之击",
      "iconUrl": "/assets/skills/paladin/302622.png",
      "sortOrder": 0
    },
    {
      "id": "paladin-302028",
      "name": "准骑士密令",
      "iconUrl": "/assets/skills/paladin/302028.png",
      "sortOrder": 1
    },
    {
      "id": "paladin-302018",
      "name": "巨锤挥击",
      "iconUrl": "/assets/skills/paladin/302018.png",
      "sortOrder": 2
    },
    {
      "id": "paladin-302662",
      "name": "崇高裁决/崇高烙印",
      "iconUrl": "/assets/skills/paladin/302662.png",
      "sortOrder": 3
    },
    {
      "id": "paladin-302073",
      "name": "突进/飞跃一击/冲天击",
      "iconUrl": "/assets/skills/paladin/302073.png",
      "sortOrder": 4
    },
    {
      "id": "paladin-302093",
      "name": "连环环破",
      "iconUrl": "/assets/skills/paladin/302093.png",
      "sortOrder": 5
    },
    {
      "id": "paladin-302038",
      "name": "巨锤重击",
      "iconUrl": "/assets/skills/paladin/302038.png",
      "sortOrder": 6
    },
    {
      "id": "paladin-302108",
      "name": "圣域",
      "iconUrl": "/assets/skills/paladin/302108.png",
      "sortOrder": 7
    },
    {
      "id": "paladin-302201",
      "name": "毁灭",
      "iconUrl": "/assets/skills/paladin/302201.png",
      "sortOrder": 8
    }
  ],
  "ice-lightning": [
    {
      "id": "ice-lightning-307001",
      "name": "冰椎剑",
      "iconUrl": "/assets/skills/ice-lightning/307001.png",
      "sortOrder": 0
    },
    {
      "id": "ice-lightning-307011",
      "name": "雷电术",
      "iconUrl": "/assets/skills/ice-lightning/307011.png",
      "sortOrder": 1
    },
    {
      "id": "ice-lightning-307511",
      "name": "寒冰迅移",
      "iconUrl": "/assets/skills/ice-lightning/307511.png",
      "sortOrder": 2
    },
    {
      "id": "ice-lightning-307021",
      "name": "冰咆哮",
      "iconUrl": "/assets/skills/ice-lightning/307021.png",
      "sortOrder": 3
    },
    {
      "id": "ice-lightning-307031",
      "name": "冰河壁",
      "iconUrl": "/assets/skills/ice-lightning/307031.png",
      "sortOrder": 4
    },
    {
      "id": "ice-lightning-307041",
      "name": "落雷枪",
      "iconUrl": "/assets/skills/ice-lightning/307041.png",
      "sortOrder": 5
    },
    {
      "id": "ice-lightning-307215",
      "name": "链环闪电",
      "iconUrl": "/assets/skills/ice-lightning/307215.png",
      "sortOrder": 6
    },
    {
      "id": "ice-lightning-307225",
      "name": "落霜冰破",
      "iconUrl": "/assets/skills/ice-lightning/307225.png",
      "sortOrder": 7
    },
    {
      "id": "ice-lightning-307056",
      "name": "寒霜爆晶",
      "iconUrl": "/assets/skills/ice-lightning/307056.png",
      "sortOrder": 8
    },
    {
      "id": "ice-lightning-307066",
      "name": "冰破魔兽",
      "iconUrl": "/assets/skills/ice-lightning/307066.png",
      "sortOrder": 9
    },
    {
      "id": "ice-lightning-307411",
      "name": "闪电矛",
      "iconUrl": "/assets/skills/ice-lightning/307411.png",
      "sortOrder": 10
    }
  ],
  "buccaneer": [
    {
      "id": "buccaneer-312512",
      "name": "水龙迸发/水龙袭击",
      "iconUrl": "/assets/skills/buccaneer/312512.png",
      "sortOrder": 0
    },
    {
      "id": "buccaneer-312020",
      "name": "震波",
      "iconUrl": "/assets/skills/buccaneer/312020.png",
      "sortOrder": 1
    },
    {
      "id": "buccaneer-312040",
      "name": "旋风踢",
      "iconUrl": "/assets/skills/buccaneer/312040.png",
      "sortOrder": 2
    },
    {
      "id": "buccaneer-312030",
      "name": "贯骨击",
      "iconUrl": "/assets/skills/buccaneer/312030.png",
      "sortOrder": 3
    },
    {
      "id": "buccaneer-312572",
      "name": "水龙爆冲/水龙袭击激怒",
      "iconUrl": "/assets/skills/buccaneer/312572.png",
      "sortOrder": 4
    },
    {
      "id": "buccaneer-312060",
      "name": "轰炸机",
      "iconUrl": "/assets/skills/buccaneer/312060.png",
      "sortOrder": 5
    },
    {
      "id": "buccaneer-312050",
      "name": "激怒拳",
      "iconUrl": "/assets/skills/buccaneer/312050.png",
      "sortOrder": 6
    },
    {
      "id": "buccaneer-312201",
      "name": "诺特勒斯战舰",
      "iconUrl": "/assets/skills/buccaneer/312201.png",
      "sortOrder": 7
    }
  ],
  "phantom": [
    {
      "id": "phantom-36005",
      "name": "双重穿刺",
      "iconUrl": "/assets/skills/phantom/36005.png",
      "sortOrder": 0
    },
    {
      "id": "phantom-36015",
      "name": "盗亦有道",
      "iconUrl": "/assets/skills/phantom/36015.png",
      "sortOrder": 1
    },
    {
      "id": "phantom-36611",
      "name": "炫目卡牌/死神卡牌",
      "iconUrl": "/assets/skills/phantom/36611.png",
      "sortOrder": 2
    },
    {
      "id": "phantom-36042",
      "name": "盗亦有道2",
      "iconUrl": "/assets/skills/phantom/36042.png",
      "sortOrder": 3
    },
    {
      "id": "phantom-36022",
      "name": "发牌",
      "iconUrl": "/assets/skills/phantom/36022.png",
      "sortOrder": 4
    },
    {
      "id": "phantom-36032",
      "name": "枫华卡浪",
      "iconUrl": "/assets/skills/phantom/36032.png",
      "sortOrder": 5
    },
    {
      "id": "phantom-36047",
      "name": "切牌",
      "iconUrl": "/assets/skills/phantom/36047.png",
      "sortOrder": 6
    },
    {
      "id": "phantom-36101",
      "name": "幻影突击",
      "iconUrl": "/assets/skills/phantom/36101.png",
      "sortOrder": 7
    },
    {
      "id": "phantom-36057",
      "name": "盗亦有道3",
      "iconUrl": "/assets/skills/phantom/36057.png",
      "sortOrder": 8
    },
    {
      "id": "phantom-36111",
      "name": "蓝光连击",
      "iconUrl": "/assets/skills/phantom/36111.png",
      "sortOrder": 9
    },
    {
      "id": "phantom-36201",
      "name": "暮光祝福",
      "iconUrl": "/assets/skills/phantom/36201.png",
      "sortOrder": 10
    },
    {
      "id": "phantom-36121",
      "name": "卡牌风暴",
      "iconUrl": "/assets/skills/phantom/36121.png",
      "sortOrder": 11
    },
    {
      "id": "phantom-36062",
      "name": "盗亦有道4",
      "iconUrl": "/assets/skills/phantom/36062.png",
      "sortOrder": 12
    },
    {
      "id": "phantom-36211",
      "name": "玫瑰卡牌之终曲",
      "iconUrl": "/assets/skills/phantom/36211.png",
      "sortOrder": 13
    }
  ],
  "shade": [
    {
      "id": "shade-37101",
      "name": "重拳闪击",
      "iconUrl": "/assets/skills/shade/37101.png",
      "sortOrder": 0
    },
    {
      "id": "shade-37401",
      "name": "灵狐",
      "iconUrl": "/assets/skills/shade/37401.png",
      "sortOrder": 1
    },
    {
      "id": "shade-37122",
      "name": "大地波动",
      "iconUrl": "/assets/skills/shade/37122.png",
      "sortOrder": 2
    },
    {
      "id": "shade-37015",
      "name": "粉碎钢刃 - 前",
      "iconUrl": "/assets/skills/shade/37015.png",
      "sortOrder": 3
    },
    {
      "id": "shade-37005",
      "name": "粉碎钢刃 - 下",
      "iconUrl": "/assets/skills/shade/37005.png",
      "sortOrder": 4
    },
    {
      "id": "shade-37025",
      "name": "粉碎钢刃 - 回",
      "iconUrl": "/assets/skills/shade/37025.png",
      "sortOrder": 5
    },
    {
      "id": "shade-37132",
      "name": "大地冲击",
      "iconUrl": "/assets/skills/shade/37132.png",
      "sortOrder": 6
    },
    {
      "id": "shade-37636",
      "name": "幻灵护魂",
      "iconUrl": "/assets/skills/shade/37636.png",
      "sortOrder": 7
    },
    {
      "id": "shade-37035",
      "name": "束缚术",
      "iconUrl": "/assets/skills/shade/37035.png",
      "sortOrder": 8
    },
    {
      "id": "shade-37142",
      "name": "灵魂帐幕",
      "iconUrl": "/assets/skills/shade/37142.png",
      "sortOrder": 9
    },
    {
      "id": "shade-37045",
      "name": "鬼斩",
      "iconUrl": "/assets/skills/shade/37045.png",
      "sortOrder": 10
    },
    {
      "id": "shade-37152",
      "name": "爆流拳",
      "iconUrl": "/assets/skills/shade/37152.png",
      "sortOrder": 11
    },
    {
      "id": "shade-37055",
      "name": "幽影刻印",
      "iconUrl": "/assets/skills/shade/37055.png",
      "sortOrder": 12
    },
    {
      "id": "shade-37065",
      "name": "业火分魂",
      "iconUrl": "/assets/skills/shade/37065.png",
      "sortOrder": 13
    },
    {
      "id": "shade-37162",
      "name": "精灵化身",
      "iconUrl": "/assets/skills/shade/37162.png",
      "sortOrder": 14
    }
  ],
  "battle-mage": [
    {
      "id": "battle-mage-39000",
      "name": "三重冲击",
      "iconUrl": "/assets/skills/battle-mage/39000.png",
      "sortOrder": 0
    },
    {
      "id": "battle-mage-39501",
      "name": "死神召唤",
      "iconUrl": "/assets/skills/battle-mage/39501.png",
      "sortOrder": 1
    },
    {
      "id": "battle-mage-39020",
      "name": "黑色锁链",
      "iconUrl": "/assets/skills/battle-mage/39020.png",
      "sortOrder": 2
    },
    {
      "id": "battle-mage-39010",
      "name": "四重冲击",
      "iconUrl": "/assets/skills/battle-mage/39010.png",
      "sortOrder": 3
    },
    {
      "id": "battle-mage-39030",
      "name": "五重冲击",
      "iconUrl": "/assets/skills/battle-mage/39030.png",
      "sortOrder": 4
    },
    {
      "id": "battle-mage-39416",
      "name": "黑暗闪电",
      "iconUrl": "/assets/skills/battle-mage/39416.png",
      "sortOrder": 5
    },
    {
      "id": "battle-mage-39040",
      "name": "战法突击",
      "iconUrl": "/assets/skills/battle-mage/39040.png",
      "sortOrder": 6
    },
    {
      "id": "battle-mage-39050",
      "name": "致命冲击",
      "iconUrl": "/assets/skills/battle-mage/39050.png",
      "sortOrder": 7
    },
    {
      "id": "battle-mage-39201",
      "name": "黑暗创世",
      "iconUrl": "/assets/skills/battle-mage/39201.png",
      "sortOrder": 8
    },
    {
      "id": "battle-mage-39064",
      "name": "斗战破军",
      "iconUrl": "/assets/skills/battle-mage/39064.png",
      "sortOrder": 9
    }
  ],
  "pathfinder": [
    {
      "id": "pathfinder-61130",
      "name": "暗红释魂",
      "iconUrl": "/assets/skills/pathfinder/61130.png",
      "sortOrder": 0
    },
    {
      "id": "pathfinder-61023",
      "name": "暗红星爆",
      "iconUrl": "/assets/skills/pathfinder/61023.png",
      "sortOrder": 1
    },
    {
      "id": "pathfinder-61048",
      "name": "精神之箭",
      "iconUrl": "/assets/skills/pathfinder/61048.png",
      "sortOrder": 2
    },
    {
      "id": "pathfinder-62045",
      "name": "暗红转移",
      "iconUrl": "/assets/skills/pathfinder/62045.png",
      "sortOrder": 3
    },
    {
      "id": "pathfinder-61078",
      "name": "渡鸦",
      "iconUrl": "/assets/skills/pathfinder/61078.png",
      "sortOrder": 4
    },
    {
      "id": "pathfinder-61058",
      "name": "黑暗三重奏",
      "iconUrl": "/assets/skills/pathfinder/61058.png",
      "sortOrder": 5
    },
    {
      "id": "pathfinder-61113",
      "name": "共振之刃",
      "iconUrl": "/assets/skills/pathfinder/61113.png",
      "sortOrder": 6
    },
    {
      "id": "pathfinder-62065",
      "name": "连珠突袭",
      "iconUrl": "/assets/skills/pathfinder/62065.png",
      "sortOrder": 7
    },
    {
      "id": "pathfinder-62041",
      "name": "远古杀阵",
      "iconUrl": "/assets/skills/pathfinder/62041.png",
      "sortOrder": 8
    }
  ],
  "wild-hunter": [
    {
      "id": "wild-hunter-41303",
      "name": "二连射/连环多箭/狂野射击",
      "iconUrl": "/assets/skills/wild-hunter/41303.png",
      "sortOrder": 0
    },
    {
      "id": "wild-hunter-41013",
      "name": "召唤玄豹",
      "iconUrl": "/assets/skills/wild-hunter/41013.png",
      "sortOrder": 1
    },
    {
      "id": "wild-hunter-41018",
      "name": "利爪狂风",
      "iconUrl": "/assets/skills/wild-hunter/41018.png",
      "sortOrder": 2
    },
    {
      "id": "wild-hunter-41616",
      "name": "终极弓弩",
      "iconUrl": "/assets/skills/wild-hunter/41616.png",
      "sortOrder": 3
    },
    {
      "id": "wild-hunter-41023",
      "name": "十字攻击/白炽冲撞",
      "iconUrl": "/assets/skills/wild-hunter/41023.png",
      "sortOrder": 4
    },
    {
      "id": "wild-hunter-41063",
      "name": "辅助打猎装置",
      "iconUrl": "/assets/skills/wild-hunter/41063.png",
      "sortOrder": 5
    },
    {
      "id": "wild-hunter-41043",
      "name": "毁灭音爆/玄豹灵魂",
      "iconUrl": "/assets/skills/wild-hunter/41043.png",
      "sortOrder": 6
    },
    {
      "id": "wild-hunter-41083",
      "name": "集束箭",
      "iconUrl": "/assets/skills/wild-hunter/41083.png",
      "sortOrder": 7
    },
    {
      "id": "wild-hunter-41551",
      "name": "奥义箭乱舞",
      "iconUrl": "/assets/skills/wild-hunter/41551.png",
      "sortOrder": 8
    },
    {
      "id": "wild-hunter-41093",
      "name": "狂暴合一/闪光箭雨",
      "iconUrl": "/assets/skills/wild-hunter/41093.png",
      "sortOrder": 9
    }
  ],
  "fire-poison": [
    {
      "id": "fire-poison-308001",
      "name": "火焰宝珠",
      "iconUrl": "/assets/skills/fire-poison/308001.png",
      "sortOrder": 0
    },
    {
      "id": "fire-poison-308011",
      "name": "迷雾",
      "iconUrl": "/assets/skills/fire-poison/308011.png",
      "sortOrder": 1
    },
    {
      "id": "fire-poison-308411",
      "name": "燎原之火",
      "iconUrl": "/assets/skills/fire-poison/308411.png",
      "sortOrder": 2
    },
    {
      "id": "fire-poison-308021",
      "name": "末日烈焰",
      "iconUrl": "/assets/skills/fire-poison/308021.png",
      "sortOrder": 3
    },
    {
      "id": "fire-poison-308421",
      "name": "快速移动精通（火毒）/污染领域",
      "iconUrl": "/assets/skills/fire-poison/308421.png",
      "sortOrder": 4
    },
    {
      "id": "fire-poison-308031",
      "name": "迷雾缠绕",
      "iconUrl": "/assets/skills/fire-poison/308031.png",
      "sortOrder": 5
    },
    {
      "id": "fire-poison-308051",
      "name": "烈焰漩涡",
      "iconUrl": "/assets/skills/fire-poison/308051.png",
      "sortOrder": 6
    },
    {
      "id": "fire-poison-308225",
      "name": "迷雾爆发",
      "iconUrl": "/assets/skills/fire-poison/308225.png",
      "sortOrder": 7
    },
    {
      "id": "fire-poison-308046",
      "name": "火魔兽",
      "iconUrl": "/assets/skills/fire-poison/308046.png",
      "sortOrder": 8
    },
    {
      "id": "fire-poison-308215",
      "name": "炙焰笼罩",
      "iconUrl": "/assets/skills/fire-poison/308215.png",
      "sortOrder": 9
    },
    {
      "id": "fire-poison-308235",
      "name": "天降陨星",
      "iconUrl": "/assets/skills/fire-poison/308235.png",
      "sortOrder": 10
    },
    {
      "id": "fire-poison-308432",
      "name": "火焰灵气",
      "iconUrl": "/assets/skills/fire-poison/308432.png",
      "sortOrder": 11
    },
    {
      "id": "fire-poison-308245",
      "name": "蓝焰业火",
      "iconUrl": "/assets/skills/fire-poison/308245.png",
      "sortOrder": 12
    }
  ],
  "demon-slayer": [
    {
      "id": "demon-slayer-43501",
      "name": "恶魔狂斩",
      "iconUrl": "/assets/skills/demon-slayer/43501.png",
      "sortOrder": 0
    },
    {
      "id": "demon-slayer-43201",
      "name": "恶魔镰刀",
      "iconUrl": "/assets/skills/demon-slayer/43201.png",
      "sortOrder": 1
    },
    {
      "id": "demon-slayer-43211",
      "name": "噬魂",
      "iconUrl": "/assets/skills/demon-slayer/43211.png",
      "sortOrder": 2
    },
    {
      "id": "demon-slayer-43021",
      "name": "黑暗疾风步",
      "iconUrl": "/assets/skills/demon-slayer/43021.png",
      "sortOrder": 3
    },
    {
      "id": "demon-slayer-43231",
      "name": "恶魔追击",
      "iconUrl": "/assets/skills/demon-slayer/43231.png",
      "sortOrder": 4
    },
    {
      "id": "demon-slayer-43031",
      "name": "黑暗审判",
      "iconUrl": "/assets/skills/demon-slayer/43031.png",
      "sortOrder": 5
    },
    {
      "id": "demon-slayer-43041",
      "name": "夺命牵引",
      "iconUrl": "/assets/skills/demon-slayer/43041.png",
      "sortOrder": 6
    },
    {
      "id": "demon-slayer-43051",
      "name": "赤红渡鸦",
      "iconUrl": "/assets/skills/demon-slayer/43051.png",
      "sortOrder": 7
    },
    {
      "id": "demon-slayer-43221",
      "name": "恶魔呼吸",
      "iconUrl": "/assets/skills/demon-slayer/43221.png",
      "sortOrder": 8
    },
    {
      "id": "demon-slayer-43061",
      "name": "恶魔末日烈焰",
      "iconUrl": "/assets/skills/demon-slayer/43061.png",
      "sortOrder": 9
    },
    {
      "id": "demon-slayer-43071",
      "name": "恶魔冲击",
      "iconUrl": "/assets/skills/demon-slayer/43071.png",
      "sortOrder": 10
    },
    {
      "id": "demon-slayer-43081",
      "name": "恶魔嘶吼",
      "iconUrl": "/assets/skills/demon-slayer/43081.png",
      "sortOrder": 11
    },
    {
      "id": "demon-slayer-43091",
      "name": "黑暗束缚",
      "iconUrl": "/assets/skills/demon-slayer/43091.png",
      "sortOrder": 12
    },
    {
      "id": "demon-slayer-43311",
      "name": "黑暗变形",
      "iconUrl": "/assets/skills/demon-slayer/43311.png",
      "sortOrder": 13
    },
    {
      "id": "demon-slayer-43101",
      "name": "冥狱夺魂",
      "iconUrl": "/assets/skills/demon-slayer/43101.png",
      "sortOrder": 14
    }
  ],
  "demon-avenger": [
    {
      "id": "demon-avenger-44005",
      "name": "超越：十字斩",
      "iconUrl": "/assets/skills/demon-avenger/44005.png",
      "sortOrder": 0
    },
    {
      "id": "demon-avenger-44065",
      "name": "暗影蝙蝠",
      "iconUrl": "/assets/skills/demon-avenger/44065.png",
      "sortOrder": 1
    },
    {
      "id": "demon-avenger-44035",
      "name": "超越：恶魔风暴",
      "iconUrl": "/assets/skills/demon-avenger/44035.png",
      "sortOrder": 2
    },
    {
      "id": "demon-avenger-44070",
      "name": "超越：月光斩",
      "iconUrl": "/assets/skills/demon-avenger/44070.png",
      "sortOrder": 3
    },
    {
      "id": "demon-avenger-44211",
      "name": "盾牌冲锋",
      "iconUrl": "/assets/skills/demon-avenger/44211.png",
      "sortOrder": 4
    },
    {
      "id": "demon-avenger-44201",
      "name": "活力吞噬",
      "iconUrl": "/assets/skills/demon-avenger/44201.png",
      "sortOrder": 5
    },
    {
      "id": "demon-avenger-44100",
      "name": "超越：逆十字斩",
      "iconUrl": "/assets/skills/demon-avenger/44100.png",
      "sortOrder": 6
    },
    {
      "id": "demon-avenger-44130",
      "name": "盾牌追击",
      "iconUrl": "/assets/skills/demon-avenger/44130.png",
      "sortOrder": 7
    },
    {
      "id": "demon-avenger-44574",
      "name": "强化超越",
      "iconUrl": "/assets/skills/demon-avenger/44574.png",
      "sortOrder": 8
    },
    {
      "id": "demon-avenger-44140",
      "name": "防御粉碎",
      "iconUrl": "/assets/skills/demon-avenger/44140.png",
      "sortOrder": 9
    },
    {
      "id": "demon-avenger-44150",
      "name": "腥红禁锢",
      "iconUrl": "/assets/skills/demon-avenger/44150.png",
      "sortOrder": 10
    },
    {
      "id": "demon-avenger-44160",
      "name": "万剑瞬斩",
      "iconUrl": "/assets/skills/demon-avenger/44160.png",
      "sortOrder": 11
    }
  ],
  "mechanic": [
    {
      "id": "mechanic-40000",
      "name": "钻臂冲击",
      "iconUrl": "/assets/skills/mechanic/40000.png",
      "sortOrder": 0
    },
    {
      "id": "mechanic-40350",
      "name": "火箭推进器",
      "iconUrl": "/assets/skills/mechanic/40350.png",
      "sortOrder": 1
    },
    {
      "id": "mechanic-40202",
      "name": "机枪扫射",
      "iconUrl": "/assets/skills/mechanic/40202.png",
      "sortOrder": 2
    },
    {
      "id": "mechanic-40212",
      "name": "进阶机枪扫射",
      "iconUrl": "/assets/skills/mechanic/40212.png",
      "sortOrder": 3
    },
    {
      "id": "mechanic-40222",
      "name": "追踪导弹",
      "iconUrl": "/assets/skills/mechanic/40222.png",
      "sortOrder": 4
    },
    {
      "id": "mechanic-40025",
      "name": "机甲大炮：代号7",
      "iconUrl": "/assets/skills/mechanic/40025.png",
      "sortOrder": 5
    },
    {
      "id": "mechanic-40301",
      "name": "火箭拳",
      "iconUrl": "/assets/skills/mechanic/40301.png",
      "sortOrder": 6
    },
    {
      "id": "mechanic-40051",
      "name": "巨型火炮：散弹",
      "iconUrl": "/assets/skills/mechanic/40051.png",
      "sortOrder": 7
    },
    {
      "id": "mechanic-40030",
      "name": "支援波动器：代号5",
      "iconUrl": "/assets/skills/mechanic/40030.png",
      "sortOrder": 8
    },
    {
      "id": "mechanic-40015",
      "name": "磁场",
      "iconUrl": "/assets/skills/mechanic/40015.png",
      "sortOrder": 9
    },
    {
      "id": "mechanic-40257",
      "name": "战争机器：泰坦",
      "iconUrl": "/assets/skills/mechanic/40257.png",
      "sortOrder": 10
    },
    {
      "id": "mechanic-40355",
      "name": "强化巨型火炮：散弹",
      "iconUrl": "/assets/skills/mechanic/40355.png",
      "sortOrder": 11
    },
    {
      "id": "mechanic-40035",
      "name": "机器人工厂：代号1",
      "iconUrl": "/assets/skills/mechanic/40035.png",
      "sortOrder": 12
    },
    {
      "id": "mechanic-40071",
      "name": "扭曲空间",
      "iconUrl": "/assets/skills/mechanic/40071.png",
      "sortOrder": 13
    }
  ],
  "cannoneer": [
    {
      "id": "cannoneer-313001",
      "name": "溅射炮",
      "iconUrl": "/assets/skills/cannoneer/313001.png",
      "sortOrder": 0
    },
    {
      "id": "cannoneer-313011",
      "name": "紧急后撤",
      "iconUrl": "/assets/skills/cannoneer/313011.png",
      "sortOrder": 1
    },
    {
      "id": "cannoneer-313021",
      "name": "炮击拳",
      "iconUrl": "/assets/skills/cannoneer/313021.png",
      "sortOrder": 2
    },
    {
      "id": "cannoneer-313031",
      "name": "强击炮",
      "iconUrl": "/assets/skills/cannoneer/313031.png",
      "sortOrder": 3
    },
    {
      "id": "cannoneer-313202",
      "name": "奇兵炸药桶",
      "iconUrl": "/assets/skills/cannoneer/313202.png",
      "sortOrder": 4
    },
    {
      "id": "cannoneer-313041",
      "name": "穿甲炮",
      "iconUrl": "/assets/skills/cannoneer/313041.png",
      "sortOrder": 5
    },
    {
      "id": "cannoneer-313222",
      "name": "奇兵爆弹/迷你火炮",
      "iconUrl": "/assets/skills/cannoneer/313222.png",
      "sortOrder": 6
    },
    {
      "id": "cannoneer-313232",
      "name": "集中炮击",
      "iconUrl": "/assets/skills/cannoneer/313232.png",
      "sortOrder": 7
    },
    {
      "id": "cannoneer-313051",
      "name": "加农火箭炮",
      "iconUrl": "/assets/skills/cannoneer/313051.png",
      "sortOrder": 8
    },
    {
      "id": "cannoneer-313066",
      "name": "双子奇兵",
      "iconUrl": "/assets/skills/cannoneer/313066.png",
      "sortOrder": 9
    },
    {
      "id": "cannoneer-313061",
      "name": "磁性船锚",
      "iconUrl": "/assets/skills/cannoneer/313061.png",
      "sortOrder": 10
    },
    {
      "id": "cannoneer-313242",
      "name": "诺特勒斯战舰",
      "iconUrl": "/assets/skills/cannoneer/313242.png",
      "sortOrder": 11
    },
    {
      "id": "cannoneer-313071",
      "name": "旋转彩虹炮",
      "iconUrl": "/assets/skills/cannoneer/313071.png",
      "sortOrder": 12
    }
  ],
  "xenon": [
    {
      "id": "xenon-45306",
      "name": "精准火箭",
      "iconUrl": "/assets/skills/xenon/45306.png",
      "sortOrder": 0
    },
    {
      "id": "xenon-45005",
      "name": "能量曲线",
      "iconUrl": "/assets/skills/xenon/45005.png",
      "sortOrder": 1
    },
    {
      "id": "xenon-45021",
      "name": "银色快剑：集中/银色快剑：闪光/银色快剑：跳跃",
      "iconUrl": "/assets/skills/xenon/45021.png",
      "sortOrder": 2
    },
    {
      "id": "xenon-45201",
      "name": "原子推进器",
      "iconUrl": "/assets/skills/xenon/45201.png",
      "sortOrder": 3
    },
    {
      "id": "xenon-45536",
      "name": "三角进攻",
      "iconUrl": "/assets/skills/xenon/45536.png",
      "sortOrder": 4
    },
    {
      "id": "xenon-45211",
      "name": "斜线追击",
      "iconUrl": "/assets/skills/xenon/45211.png",
      "sortOrder": 5
    },
    {
      "id": "xenon-45081",
      "name": "反重力力场",
      "iconUrl": "/assets/skills/xenon/45081.png",
      "sortOrder": 6
    },
    {
      "id": "xenon-45051",
      "name": "战斗切换：破空/战斗切换：爆炸/战斗切换：分裂",
      "iconUrl": "/assets/skills/xenon/45051.png",
      "sortOrder": 7
    },
    {
      "id": "xenon-45336",
      "name": "宙斯盾系统",
      "iconUrl": "/assets/skills/xenon/45336.png",
      "sortOrder": 8
    },
    {
      "id": "xenon-45221",
      "name": "刀锋之舞",
      "iconUrl": "/assets/skills/xenon/45221.png",
      "sortOrder": 9
    },
    {
      "id": "xenon-45091",
      "name": "聚能脉冲炮：炮击/聚能脉冲炮：爆击/聚能脉冲炮：狙击",
      "iconUrl": "/assets/skills/xenon/45091.png",
      "sortOrder": 10
    },
    {
      "id": "xenon-45121",
      "name": "全息力场：领域/全息力场：支援/全息力场：穿透",
      "iconUrl": "/assets/skills/xenon/45121.png",
      "sortOrder": 11
    },
    {
      "id": "xenon-45141",
      "name": "禁锢束缚",
      "iconUrl": "/assets/skills/xenon/45141.png",
      "sortOrder": 12
    },
    {
      "id": "xenon-45142",
      "name": "诸天毁灭之光",
      "iconUrl": "/assets/skills/xenon/45142.png",
      "sortOrder": 13
    }
  ],
  "angelic-buster": [
    {
      "id": "angelic-buster-114701",
      "name": "释世书",
      "iconUrl": "/assets/skills/angelic-buster/114701.png",
      "sortOrder": 0
    },
    {
      "id": "angelic-buster-114002",
      "name": "泡沫之星",
      "iconUrl": "/assets/skills/angelic-buster/114002.png",
      "sortOrder": 1
    },
    {
      "id": "angelic-buster-114015",
      "name": "穿刺爆炸",
      "iconUrl": "/assets/skills/angelic-buster/114015.png",
      "sortOrder": 2
    },
    {
      "id": "angelic-buster-114025",
      "name": "粉粉旋风",
      "iconUrl": "/assets/skills/angelic-buster/114025.png",
      "sortOrder": 3
    },
    {
      "id": "angelic-buster-114035",
      "name": "灵魂追击者",
      "iconUrl": "/assets/skills/angelic-buster/114035.png",
      "sortOrder": 4
    },
    {
      "id": "angelic-buster-114045",
      "name": "行星撞击",
      "iconUrl": "/assets/skills/angelic-buster/114045.png",
      "sortOrder": 5
    },
    {
      "id": "angelic-buster-114055",
      "name": "原始之吼",
      "iconUrl": "/assets/skills/angelic-buster/114055.png",
      "sortOrder": 6
    },
    {
      "id": "angelic-buster-114075",
      "name": "大地冲击波",
      "iconUrl": "/assets/skills/angelic-buster/114075.png",
      "sortOrder": 7
    },
    {
      "id": "angelic-buster-114502",
      "name": "灵魂共鸣",
      "iconUrl": "/assets/skills/angelic-buster/114502.png",
      "sortOrder": 8
    },
    {
      "id": "angelic-buster-114065",
      "name": "三位一体",
      "iconUrl": "/assets/skills/angelic-buster/114065.png",
      "sortOrder": 9
    },
    {
      "id": "angelic-buster-114085",
      "name": "超级诺巴",
      "iconUrl": "/assets/skills/angelic-buster/114085.png",
      "sortOrder": 10
    }
  ],
  "kaiser": [
    {
      "id": "kaiser-47601",
      "name": "飞龙斩",
      "iconUrl": "/assets/skills/kaiser/47601.png",
      "sortOrder": 0
    },
    {
      "id": "kaiser-47016",
      "name": "烈火箭",
      "iconUrl": "/assets/skills/kaiser/47016.png",
      "sortOrder": 1
    },
    {
      "id": "kaiser-47036",
      "name": "冲击波",
      "iconUrl": "/assets/skills/kaiser/47036.png",
      "sortOrder": 2
    },
    {
      "id": "kaiser-47056",
      "name": "穿刺冲击",
      "iconUrl": "/assets/skills/kaiser/47056.png",
      "sortOrder": 3
    },
    {
      "id": "kaiser-47417",
      "name": "‎剑刃之壁",
      "iconUrl": "/assets/skills/kaiser/47417.png",
      "sortOrder": 4
    },
    {
      "id": "kaiser-47116",
      "name": "扇击",
      "iconUrl": "/assets/skills/kaiser/47116.png",
      "sortOrder": 5
    },
    {
      "id": "kaiser-47096",
      "name": "石化",
      "iconUrl": "/assets/skills/kaiser/47096.png",
      "sortOrder": 6
    },
    {
      "id": "kaiser-47076",
      "name": "牵引锁链",
      "iconUrl": "/assets/skills/kaiser/47076.png",
      "sortOrder": 7
    },
    {
      "id": "kaiser-47176",
      "name": "‎怒雷屠龙斩",
      "iconUrl": "/assets/skills/kaiser/47176.png",
      "sortOrder": 8
    },
    {
      "id": "kaiser-47196",
      "name": "天空剑影",
      "iconUrl": "/assets/skills/kaiser/47196.png",
      "sortOrder": 9
    },
    {
      "id": "kaiser-47136",
      "name": "剑气突袭",
      "iconUrl": "/assets/skills/kaiser/47136.png",
      "sortOrder": 10
    },
    {
      "id": "kaiser-47216",
      "name": "‎恶魔之息",
      "iconUrl": "/assets/skills/kaiser/47216.png",
      "sortOrder": 11
    },
    {
      "id": "kaiser-47236",
      "name": "日珥",
      "iconUrl": "/assets/skills/kaiser/47236.png",
      "sortOrder": 12
    }
  ],
  "dual-blade": [
    {
      "id": "dual-blade-305003",
      "name": "快刀斩",
      "iconUrl": "/assets/skills/dual-blade/305003.png",
      "sortOrder": 0
    },
    {
      "id": "dual-blade-305013",
      "name": "龙卷风",
      "iconUrl": "/assets/skills/dual-blade/305013.png",
      "sortOrder": 1
    },
    {
      "id": "dual-blade-305023",
      "name": "流云斩",
      "iconUrl": "/assets/skills/dual-blade/305023.png",
      "sortOrder": 2
    },
    {
      "id": "dual-blade-305033",
      "name": "双刀风暴",
      "iconUrl": "/assets/skills/dual-blade/305033.png",
      "sortOrder": 3
    },
    {
      "id": "dual-blade-305043",
      "name": "暗影飞跃斩",
      "iconUrl": "/assets/skills/dual-blade/305043.png",
      "sortOrder": 4
    },
    {
      "id": "dual-blade-305063",
      "name": "冽雨狂风",
      "iconUrl": "/assets/skills/dual-blade/305063.png",
      "sortOrder": 5
    },
    {
      "id": "dual-blade-305301",
      "name": "地狱锁链",
      "iconUrl": "/assets/skills/dual-blade/305301.png",
      "sortOrder": 6
    },
    {
      "id": "dual-blade-305073",
      "name": "奔腾之刃",
      "iconUrl": "/assets/skills/dual-blade/305073.png",
      "sortOrder": 7
    },
    {
      "id": "dual-blade-305093",
      "name": "幽灵一击",
      "iconUrl": "/assets/skills/dual-blade/305093.png",
      "sortOrder": 8
    },
    {
      "id": "dual-blade-305311",
      "name": "暴怒刀阵",
      "iconUrl": "/assets/skills/dual-blade/305311.png",
      "sortOrder": 9
    },
    {
      "id": "dual-blade-305321",
      "name": "终极斩",
      "iconUrl": "/assets/skills/dual-blade/305321.png",
      "sortOrder": 10
    },
    {
      "id": "dual-blade-305103",
      "name": "突然袭击",
      "iconUrl": "/assets/skills/dual-blade/305103.png",
      "sortOrder": 11
    },
    {
      "id": "dual-blade-305411",
      "name": "隐形剑",
      "iconUrl": "/assets/skills/dual-blade/305411.png",
      "sortOrder": 12
    },
    {
      "id": "dual-blade-305331",
      "name": "阿修罗",
      "iconUrl": "/assets/skills/dual-blade/305331.png",
      "sortOrder": 13
    },
    {
      "id": "dual-blade-305681",
      "name": "精准刀",
      "iconUrl": "/assets/skills/dual-blade/305681.png",
      "sortOrder": 14
    }
  ],
  "kinesis": [
    {
      "id": "kinesis-67012",
      "name": "心魂之力",
      "iconUrl": "/assets/skills/kinesis/67012.png",
      "sortOrder": 0
    },
    {
      "id": "kinesis-67062",
      "name": "‎终极 - 物质",
      "iconUrl": "/assets/skills/kinesis/67062.png",
      "sortOrder": 1
    },
    {
      "id": "kinesis-67002",
      "name": "心灵爆震",
      "iconUrl": "/assets/skills/kinesis/67002.png",
      "sortOrder": 2
    },
    {
      "id": "kinesis-67073",
      "name": "‎疯狂爆震",
      "iconUrl": "/assets/skills/kinesis/67073.png",
      "sortOrder": 3
    },
    {
      "id": "kinesis-67083",
      "name": "心魂吸收",
      "iconUrl": "/assets/skills/kinesis/67083.png",
      "sortOrder": 4
    },
    {
      "id": "kinesis-67093",
      "name": "‎终极 - 深层冲击",
      "iconUrl": "/assets/skills/kinesis/67093.png",
      "sortOrder": 5
    },
    {
      "id": "kinesis-67103",
      "name": "心魂之手",
      "iconUrl": "/assets/skills/kinesis/67103.png",
      "sortOrder": 6
    },
    {
      "id": "kinesis-67153",
      "name": "终极 - 火车",
      "iconUrl": "/assets/skills/kinesis/67153.png",
      "sortOrder": 7
    },
    {
      "id": "kinesis-67451",
      "name": "心灵传动",
      "iconUrl": "/assets/skills/kinesis/67451.png",
      "sortOrder": 8
    },
    {
      "id": "kinesis-67721",
      "name": "终极 - 速率",
      "iconUrl": "/assets/skills/kinesis/67721.png",
      "sortOrder": 9
    },
    {
      "id": "kinesis-67193",
      "name": "‎心魂释放",
      "iconUrl": "/assets/skills/kinesis/67193.png",
      "sortOrder": 10
    },
    {
      "id": "kinesis-67194",
      "name": "‎心灵侵蚀",
      "iconUrl": "/assets/skills/kinesis/67194.png",
      "sortOrder": 11
    }
  ],
  "adele": [
    {
      "id": "adele-86005",
      "name": "本能",
      "iconUrl": "/assets/skills/adele/86005.png",
      "sortOrder": 0
    },
    {
      "id": "adele-86401",
      "name": "夏德/出神",
      "iconUrl": "/assets/skills/adele/86401.png",
      "sortOrder": 1
    },
    {
      "id": "adele-86016",
      "name": "剑刺",
      "iconUrl": "/assets/skills/adele/86016.png",
      "sortOrder": 2
    },
    {
      "id": "adele-86206",
      "name": "十字穿叉",
      "iconUrl": "/assets/skills/adele/86206.png",
      "sortOrder": 3
    },
    {
      "id": "adele-86306",
      "name": "缔造/御剑收鞘",
      "iconUrl": "/assets/skills/adele/86306.png",
      "sortOrder": 4
    },
    {
      "id": "adele-86026",
      "name": "御剑穿刺/共振/标记",
      "iconUrl": "/assets/skills/adele/86026.png",
      "sortOrder": 5
    },
    {
      "id": "adele-86216",
      "name": "御剑追击/剑咒之印",
      "iconUrl": "/assets/skills/adele/86216.png",
      "sortOrder": 6
    },
    {
      "id": "adele-86246",
      "name": "斩决",
      "iconUrl": "/assets/skills/adele/86246.png",
      "sortOrder": 7
    },
    {
      "id": "adele-86236",
      "name": "剑域/触底",
      "iconUrl": "/assets/skills/adele/86236.png",
      "sortOrder": 8
    },
    {
      "id": "adele-86276",
      "name": "盛放之剑/暴风剑狱",
      "iconUrl": "/assets/skills/adele/86276.png",
      "sortOrder": 9
    }
  ],
  "sia": [
    {
      "id": "sia-76701",
      "name": "恒星I - 兔子座/光线",
      "iconUrl": "/assets/skills/sia/76701.png",
      "sortOrder": 0
    },
    {
      "id": "sia-76711",
      "name": "恒星II - 蜥蜴座/爆炸",
      "iconUrl": "/assets/skills/sia/76711.png",
      "sortOrder": 1
    },
    {
      "id": "sia-76741",
      "name": "恒星V - 角螺座/极点",
      "iconUrl": "/assets/skills/sia/76741.png",
      "sortOrder": 2
    },
    {
      "id": "sia-76502",
      "name": "星光",
      "iconUrl": "/assets/skills/sia/76502.png",
      "sortOrder": 3
    },
    {
      "id": "sia-76751",
      "name": "恒星VI - 暗影面具座/恒星VII - 老鹰座/连结",
      "iconUrl": "/assets/skills/sia/76751.png",
      "sortOrder": 4
    },
    {
      "id": "sia-76772",
      "name": "恒星IX - 冒险之锚座",
      "iconUrl": "/assets/skills/sia/76772.png",
      "sortOrder": 5
    }
  ],
  "erel": [
    {
      "id": "erel-115006",
      "name": "破晓之枪/指令守卫",
      "iconUrl": "/assets/skills/erel/115006.png",
      "sortOrder": 0
    },
    {
      "id": "erel-115016",
      "name": "圣耀之怒/圣耀之刺",
      "iconUrl": "/assets/skills/erel/115016.png",
      "sortOrder": 1
    },
    {
      "id": "erel-115039",
      "name": "闪耀奔袭",
      "iconUrl": "/assets/skills/erel/115039.png",
      "sortOrder": 2
    },
    {
      "id": "erel-115079",
      "name": "闪耀征途",
      "iconUrl": "/assets/skills/erel/115079.png",
      "sortOrder": 3
    },
    {
      "id": "erel-115413",
      "name": "星光穿刺",
      "iconUrl": "/assets/skills/erel/115413.png",
      "sortOrder": 4
    },
    {
      "id": "erel-115119",
      "name": "星光天坠",
      "iconUrl": "/assets/skills/erel/115119.png",
      "sortOrder": 5
    }
  ],
  "mo-xuan": [
    {
      "id": "mo-xuan-111006",
      "name": "玄山：招式全开",
      "iconUrl": "/assets/skills/mo-xuan/111006.png",
      "sortOrder": 0
    },
    {
      "id": "mo-xuan-111017",
      "name": "神功：破碎拳",
      "iconUrl": "/assets/skills/mo-xuan/111017.png",
      "sortOrder": 1
    },
    {
      "id": "mo-xuan-111057",
      "name": "神功：旋风脚",
      "iconUrl": "/assets/skills/mo-xuan/111057.png",
      "sortOrder": 2
    },
    {
      "id": "mo-xuan-111087",
      "name": "神功：铁山靠",
      "iconUrl": "/assets/skills/mo-xuan/111087.png",
      "sortOrder": 3
    },
    {
      "id": "mo-xuan-111528",
      "name": "神功：乱拳连击",
      "iconUrl": "/assets/skills/mo-xuan/111528.png",
      "sortOrder": 4
    },
    {
      "id": "mo-xuan-111137",
      "name": "神功：无影脚",
      "iconUrl": "/assets/skills/mo-xuan/111137.png",
      "sortOrder": 5
    },
    {
      "id": "mo-xuan-111157",
      "name": "秘技：千斤锤",
      "iconUrl": "/assets/skills/mo-xuan/111157.png",
      "sortOrder": 6
    },
    {
      "id": "mo-xuan-111202",
      "name": "神功：大地崩裂",
      "iconUrl": "/assets/skills/mo-xuan/111202.png",
      "sortOrder": 7
    },
    {
      "id": "mo-xuan-84115",
      "name": "神功：移形换位",
      "iconUrl": "/assets/skills/mo-xuan/84115.png",
      "sortOrder": 8
    },
    {
      "id": "mo-xuan-111232",
      "name": "真气：焦热破神击",
      "iconUrl": "/assets/skills/mo-xuan/111232.png",
      "sortOrder": 9
    }
  ]
} as const;
