import { useMemo, useState } from 'react';
import './currency.css';
import './currency-theme.css';

const shopItems = [
  ['自动战斗补充券（1小时）', 'meso', 550, 1], ['精灵坠饰 10%', 'meso', 5000, 0], ['精灵坠饰 5%', 'meso', 2500, 0],
  ['自动战斗补充券（1小时）×5', 'red', 185, 5], ['自动战斗补充券（30分钟）×5', 'red', 100, 2.5],
] as const;
const number = (value: number, digits = 2) => new Intl.NumberFormat('zh-CN', { maximumFractionDigits: digits, minimumFractionDigits: digits }).format(value);
const integer = (value: number) => new Intl.NumberFormat('zh-CN', { maximumFractionDigits: 0 }).format(value);

export default function CurrencyPage() {
  const [rmb, setRmb] = useState(90); const [meso, setMeso] = useState(59000);
  const metrics = useMemo(() => { const safeRmb = Math.max(1, rmb); const safeMeso = Math.max(1, meso); const mesoPerRmb = safeMeso / safeRmb; const rmbPerMeso = safeRmb / safeMeso; const blueValue = 1850 * 15 * rmbPerMeso; const redPerRmb = 8550 / Math.max(.01, 185 - blueValue); return { mesoPerRmb, blueValue, redPerRmb, redRmb: 1 / redPerRmb, rawRed: 8550 / 185 }; }, [rmb, meso]);
  return <main className="currency-shell"><header className="currency-header"><div><span className="currency-brand">Maple<span>Lab</span></span><span className="currency-divider">/</span><span>枫币计算器</span></div><a href="/">伤害 DPS 模拟器</a></header><section className="currency-hero"><div><p className="currency-eyebrow">MapleStory M Currency Desk</p><h1>月卡红水晶真实效率估算器</h1><p>输入当前商人枫币价格，将 185 礼包里的蓝水晶按官方兑换枫币折成保底价值，再估算剩余成本能买到多少红水晶。</p></div><div className="currency-orb"><small>1 元 ≈</small><strong>{number(metrics.redPerRmb)}</strong><small>红水晶</small></div></section><section className="currency-workspace"><div className="currency-inputs"><p className="currency-kicker">实时输入</p><h2>当前枫币价格</h2><label>人民币价格<input type="number" value={rmb} onChange={(e) => setRmb(Number(e.target.value))} /><em>RMB</em></label><label>获得枫币<input type="number" value={meso} onChange={(e) => setMeso(Number(e.target.value))} /><em>枫币</em></label></div><div className="currency-results"><div><small>商人枫币汇率</small><strong>1 元 ≈ {number(metrics.mesoPerRmb)} 枫币</strong></div><div><small>185 礼包蓝水晶保底</small><strong>{integer(27750)} 枫币 ≈ {number(metrics.blueValue)} 元</strong></div><div><small>扣除蓝水晶后</small><strong>1 元 ≈ {number(metrics.redPerRmb)} 红水晶</strong></div></div></section><section className="currency-strip"><div><small>185 礼包固定内容</small><strong>1,850 蓝 + 8,550 红</strong></div><div><small>不扣蓝水晶时</small><strong>{number(metrics.rawRed)} 红 / 元</strong></div><div><small>蓝水晶折枫币后剩余成本</small><strong>{number(185 - metrics.blueValue)} 元</strong></div><div><small>红水晶折算单价</small><strong>{number(metrics.redRmb, 4)} 元 / 红</strong></div></section><section className="currency-shop"><div className="currency-kicker">Shop Items</div><h2>常见商店物品 RMB 估价</h2><div className="currency-table"><div className="currency-row currency-row-head"><span>物品</span><span>商店价格</span><span>RMB 估价</span><span>每小时成本</span></div>{shopItems.map(([name, type, price, hours]) => { const value = type === 'meso' ? price / metrics.mesoPerRmb : price * metrics.redRmb; return <div className="currency-row" key={name}><span><i className={`currency-token ${type}`} />{name}</span><span>{integer(price)} {type === 'meso' ? '枫币' : '红水晶'}</span><strong>{number(value)} 元</strong><span>{hours ? `${number(value / hours)} 元 / 小时` : '—'}</span></div>; })}</div></section></main>;
}
